# Antigen
source ~/.antigen/antigen.zsh
antigen use oh-my-zsh
# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
# Theme
antigen theme dst
antigen apply

# Share history
setopt histignorealldups sharehistory
# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e
bindkey "^[h" backward-kill-word

# Use modern completion system
autoload -Uz compinit
compinit

# Alias
alias ll='ls -lF'
alias la='ls -A'
alias l='ls -CF'
alias c='coffee'
alias i="ipython --no-confirm-exit"
alias m="emacsclient --alternate-editor='' -t"
alias cleanpyc="find . -name '*.pyc' | while read line; do echo DEL \$line; rm \$line; done"
alias pj="python -mjson.tool"
alias sn="screen -S"
alias sr="screen -rd"
alias fissionsrc="/home/jwcai/Vessel/fission/node_modules/.bin/iced /home/jwcai/Vessel/fission/src/fission.coffee"

# Python Virtual Environment
export PYENV_ROOT="$HOME/.pyenv"
export GOPATH="$HOME/.gocode"
export PATH="$HOME/bin:$PYENV_ROOT/bin:$GOPATH/bin:$PATH"
eval "$(pyenv init -)"

# Node stuff
source ~/.nvm/nvm.sh

# Autojump
source /usr/share/autojump/autojump.sh
